version: "{branch} {build}"

environment:
  nodejs_version: "10"
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - ps: Install-Product node $env:nodejs_version

build:
  verbosity: detailed

build_script:
  - node --version
  - npm --version
  - ps: set
  - gradlew.bat compileJava compileTestJava --info --stacktrace --no-daemon

test_script:
  - gradlew.bat test --info --stacktrace --no-daemon

branches:
  only:
    - develop

cache:
  - C:\Users\appveyor\.gradle
